import { Passenger } from '../types/passenger';

// 测试用的模拟乘客数据
export const mockPassengers: Passenger[] = [
  {
    PassengerId: 1,
    Survived: 1,
    Pclass: 1,
    Name: 'John Smith',
    Sex: 'male',
    Age: 35,
    SibSp: 0,
    Parch: 0,
    Ticket: 'A/5 21171',
    Fare: 71.2833,
    Cabin: 'C85',
    Embarked: 'C',
    HasCabin: 1,
    Title: 'Mr',
    FamilySize: 1,
    IsAlone: 1,
    FamilySizeGroup: 'Solo',
    FareGroup: 'High',
    AgeGroup: 'Young Adult',
    Sex_encoded: 0,
    Embarked_encoded: 0,
    Title_encoded: 0,
    SurvivedLabel: 'Yes',
    PclassLabel: 'First',
    EmbarkedLabel: 'Cherbourg',
    SexLabel: 'Male',
    Age_original: 35,
    Fare_original: 71.2833,
    SibSp_original: 0,
    Parch_original: 0
  },
  {
    PassengerId: 2,
    Survived: 0,
    Pclass: 3,
    Name: 'Mary Johnson',
    Sex: 'female',
    Age: 25,
    SibSp: 1,
    Parch: 0,
    Ticket: 'PC 17599',
    Fare: 7.925,
    Cabin: null,
    Embarked: 'S',
    HasCabin: 0,
    Title: 'Miss',
    FamilySize: 2,
    IsAlone: 0,
    FamilySizeGroup: 'Small',
    FareGroup: 'Low',
    AgeGroup: 'Young Adult',
    Sex_encoded: 1,
    Embarked_encoded: 1,
    Title_encoded: 1,
    SurvivedLabel: 'No',
    PclassLabel: 'Third',
    EmbarkedLabel: 'Southampton',
    SexLabel: 'Female',
    Age_original: 25,
    Fare_original: 7.925,
    SibSp_original: 1,
    Parch_original: 0
  },
  {
    PassengerId: 3,
    Survived: 1,
    Pclass: 2,
    Name: 'Robert Brown',
    Sex: 'male',
    Age: 45,
    SibSp: 0,
    Parch: 2,
    Ticket: '113803',
    Fare: 53.1,
    Cabin: 'C123',
    Embarked: 'S',
    HasCabin: 1,
    Title: 'Mr',
    FamilySize: 3,
    IsAlone: 0,
    FamilySizeGroup: 'Small',
    FareGroup: 'High',
    AgeGroup: 'Adult',
    Sex_encoded: 0,
    Embarked_encoded: 1,
    Title_encoded: 0,
    SurvivedLabel: 'Yes',
    PclassLabel: 'Second',
    EmbarkedLabel: 'Southampton',
    SexLabel: 'Male',
    Age_original: 45,
    Fare_original: 53.1,
    SibSp_original: 0,
    Parch_original: 2
  },
  {
    PassengerId: 4,
    Survived: 0,
    Pclass: 3,
    Name: 'Sarah Davis',
    Sex: 'female',
    Age: 18,
    SibSp: 0,
    Parch: 0,
    Ticket: '330877',
    Fare: 8.4583,
    Cabin: null,
    Embarked: 'Q',
    HasCabin: 0,
    Title: 'Miss',
    FamilySize: 1,
    IsAlone: 1,
    FamilySizeGroup: 'Solo',
    FareGroup: 'Low',
    AgeGroup: 'Teen',
    Sex_encoded: 1,
    Embarked_encoded: 2,
    Title_encoded: 1,
    SurvivedLabel: 'No',
    PclassLabel: 'Third',
    EmbarkedLabel: 'Queenstown',
    SexLabel: 'Female',
    Age_original: 18,
    Fare_original: 8.4583,
    SibSp_original: 0,
    Parch_original: 0
  },
  {
    PassengerId: 5,
    Survived: 1,
    Pclass: 1,
    Name: 'William Wilson',
    Sex: 'male',
    Age: 60,
    SibSp: 1,
    Parch: 1,
    Ticket: '17463',
    Fare: 120,
    Cabin: 'B58',
    Embarked: 'C',
    HasCabin: 1,
    Title: 'Mr',
    FamilySize: 3,
    IsAlone: 0,
    FamilySizeGroup: 'Small',
    FareGroup: 'Luxury',
    AgeGroup: 'Adult',
    Sex_encoded: 0,
    Embarked_encoded: 0,
    Title_encoded: 0,
    SurvivedLabel: 'Yes',
    PclassLabel: 'First',
    EmbarkedLabel: 'Cherbourg',
    SexLabel: 'Male',
    Age_original: 60,
    Fare_original: 120,
    SibSp_original: 1,
    Parch_original: 1
  }
];

// 默认筛选器状态
export const defaultFilters = {
  survival: [],
  gender: [],
  pclass: [],
  ageGroup: [],
  familySize: [],
  fareGroup: [],
  embarked: [],
  ageRange: [0, 100] as [number, number],
  fareRange: [0, 512] as [number, number],
  searchText: ''
};